
create table if not exists "card_attachments" (
    "id" bigint generated always as identity primary key,
    "publicId" varchar(12) not null unique,
    "cardId" bigint not null references "card"("id") on delete cascade,
    "fileName" text not null,
    "fileSize" integer not null,
    "fileType" text not null,
    "filePath" text not null,
    "createdBy" uuid references "users"("id") on delete set null,
    "createdAt" timestamp with time zone default now() not null,
    "updatedAt" timestamp with time zone,
    "deletedAt" timestamp with time zone,
    "deletedBy" uuid references "users"("id") on delete set null
);

comment on table "card_attachments" is 'Stores metadata for files attached to cards.';

alter table "card"
add column if not exists "coverAttachmentId" bigint references "card_attachments"("id") on delete set null;

-- Enable RLS on card_attachments
alter table "card_attachments" enable row level security;

-- RLS Policies for card_attachments
-- Note: Access control is handled in the application layer via assertUserInWorkspace
-- These policies allow authenticated users to access attachments.
-- The application layer enforces workspace membership and board visibility checks.

-- Select: Allow access to attachments
-- Application layer controls which attachments are returned based on card access
create policy "Users can view card attachments"
on "card_attachments"
for select
using (true);

-- Insert: Allow access to insert attachments
-- Application layer validates workspace membership before allowing insert
create policy "Users can insert card attachments"
on "card_attachments"
for insert
with check (true);

-- Update: Allow access to update attachments
-- Application layer validates workspace membership before allowing update
create policy "Users can update card attachments"
on "card_attachments"
for update
using (true)
with check (true);

-- Delete: Allow access to delete attachments
-- Application layer validates workspace membership before allowing delete
create policy "Users can delete card attachments"
on "card_attachments"
for delete
using (true);

-- Note: Storage is handled by S3-compatible service (AWS S3, Cloudflare R2, MinIO, etc.)
-- The bucket 'card-attachments' should be created in your S3 service.
-- Access control is handled by presigned URLs generated by the backend.


